version: "{branch}-{build}"
skip_tags: true
shallow_clone: true
cache:
  - C:\ProgramData\chocolatey\bin -> .\build\appveyor_install.ps1
  - C:\ProgramData\chocolatey\lib -> .\build\appveyor_install.ps1
  - C:\Users\appveyor\.ccm\repository -> .\build\appveyor_install.ps1
  - C:\Users\appveyor\deps -> .\build\appveyor_install.ps1
image: Visual Studio 2019
environment:
  NUNIT_PATH: nunit3-console
  matrix:
    - TARGET: net461
      CASSANDRA_VERSION: 4.0-alpha4
      CI_TYPE: INTEGRATION_FULL
      PROJECT: Cassandra.IntegrationTests
    - TARGET: netcoreapp2.1
      CASSANDRA_VERSION: 4.0-alpha4
      CI_TYPE: INTEGRATION_FULL
      PROJECT: Cassandra.IntegrationTests
      
# init:
  # - ps: $blockRdp = $True; iex ((New-Object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - ps: .\build\appveyor_install.ps1

build_script:
  - ps: New-Item -ItemType Directory -Path "$env:USERPROFILE\.ccm\repository\4.0-alpha4"
  - appveyor DownloadFile https://dist.apache.org/repos/dist/dev/cassandra/4.0-alpha4/apache-cassandra-4.0-alpha4-bin.tar.gz
  - tar xzf apache-cassandra-4.0-alpha4-bin.tar.gz -C %USERPROFILE%\.ccm\repository\4.0-alpha4 --strip-components=1
  - ps: |
      "4.0-alpha4" | Out-File %USERPROFILE%\.ccm\repository\4.0-alpha4\0.version.txt
  - ps: dotnet --info
  - ps: dotnet restore src
  - ps: dotnet build src\Cassandra.sln -c Release

test_script:
  - ps: |
      if(${env:CI_TYPE} -eq "INTEGRATION_FULL")
      {
          dotnet test src\${env:PROJECT}\${env:PROJECT}.csproj -c Release -f $env:TARGET --filter "(TestCategory!=long)&(TestCategory!=memory)&(TestCategory!=realclusterlong)" --logger:Appveyor
      }
      else 
      {
          dotnet test src\${env:PROJECT}\${env:PROJECT}.csproj -c Release -f $env:TARGET --filter "(TestCategory!=long)&(TestCategory!=memory)&(TestCategory!=realcluster)&(TestCategory!=realclusterlong)" --logger:Appveyor
      }      
on_failure:
  - ps: |
      Write-Host "Build failed"
